version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /share/Multimedia:/media
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      #- /opt/NVIDIA_GPU_DRV/usr:/usr/local/nvidia:ro
    #environment:
      #- LD_LIBRARY_PATH=/usr/local/nvidia/lib
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.jellyfin-secure-headers.headers.framedeny=true"
      - "traefik.http.middlewares.jellyfin-secure-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.jellyfin-secure-headers.headers.browserxssfilter=true"
      - "traefik.http.middlewares.jellyfin-secure-headers.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.http.routers.jellyfin.rule=Host(`example.com`) && (PathPrefix(`/jellyfin/`) || Path(`/jellyfin`))"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=le"
      - "traefik.http.routers.jellyfin.service=jellyfin-web"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-secure-headers"
      - "traefik.http.services.jellyfin-web.loadbalancer.server.port=8096"
    #devices:
      #- /dev/nvidiactl
      #- /dev/nvidia0:/dev/nvidia0
      #- /dev/nvidia-caps:/dev/nvidia-caps
      #- /dev/nvidia-modeset:/dev/nvidia-modeset
      #- /dev/nvidia-uvm:/dev/nvidia-uvm
      #- /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      #- /dev/dri/renderD128:/dev/dri/renderD128
      #- /dev/dri/card0:/dev/dri/card0
    user: 1000:1000
    group_add:
      - '44' #video
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
        compress: "true"
    networks:
      - jellyfin
      - traefik

volumes:
  jellyfin-config:
  jellyfin-cache:

networks:
  jellyfin:
    name: jellyfin
  traefik:
    external: true
